### ISSUE TITLE
Angular 5 Error

### ISSUE THREAD

**Issue by psykolm22** [psykolm22/angular-google-place#22]
_From @mmaryo on November 14, 2017 8:10_

Hello 

This is an error that I have when I upgrade to Angular 5

Any idea ?

Thanks 

chunk {common} common.chunk.js (common) 19.1 kB  [rendered]
chunk {customers.module} customers.module.chunk.js () 72.5 kB  [rendered]
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {login.module} login.module.chunk.js () 17.8 kB  [rendered]
chunk {main} main.bundle.js (main) 2.29 MB [initial] [rendered]
chunk {settings.module} settings.module.chunk.js () 54.9 kB  [rendered]
chunk {shops.module} shops.module.chunk.js () 105 kB  [rendered]
chunk {styles} styles.bundle.js (styles) 1.26 MB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 20.7 MB [initial] [rendered]

ERROR in ./node_modules/ng2-google-place-autocomplete/index.ts
Module build failed: Error: /home/mario/dev/neptune/node_modules/ng2-google-place-autocomplete/index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/home/mario/dev/neptune/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
    at plugin.done.then (/home/mario/dev/neptune/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
 @ ./src/app/app.module.ts 105:0-66
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.

_Copied from original issue: psykolm22/ng2-google-place-autocomplete#35_

**Comment by psykolm22** [comment]
_From @abhijithmannath on November 24, 2017 15:10_

I managed to solve this issue by adding index.ts to the includes array of tsconfig.app.json like this
"include": [
    "../node_modules/ng2-google-place-autocomplete/index.ts"
]

**Comment by psykolm22** [comment]
_From @agil-NUBBA on November 27, 2017 19:4_

This is Angular 5 compiler issue, import with:
```typescript
import { GooglePlaceModule } from 'ng2-google-place-autocomplete/src';
```
and compile with `--aot`, and it will work (workarround (AKA ñapa))
```bash 
ng serve --aot
```
same hapened at [ngx-datatable](https://github.com/swimlane/ngx-datatable/issues/1104).

Also: HttpModule should be replaced by HttpClientModule https://github.com/psykolm22/ng2-google-place-autocomplete/blob/master/src/app/app.module.ts#L4

**Comment by psykolm22** [comment]
_From @fabrizziocht on December 11, 2017 1:2_

I modified my tsconfig.app.json like:

> {
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ],
  "include": [
    "**/*.ts",
    "../node_modules/ng2-google-place-autocomplete/index.ts"
    ]
}

>

also in tsconfig.json:

> {
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include": [
    "src/**/*.ts",
    "/node_modules/ng2-google-place-autocomplete/index.ts"
  ]
}


and everything works well.

**Comment by psykolm22** [comment]
Angular-google-place package should have solved it now

**Comment by nsksaisaravana** [comment]
Still i am having the same issue, if i use the above code i am getting the below error

![image](https://user-images.githubusercontent.com/17681573/41757215-f970bc00-7623-11e8-950e-64574e75894b.png)
