### ISSUE TITLE
404...

### ISSUE THREAD

**Issue by owilkening** [psykolm22/angular-google-place#27]
I ran through the tutorial through and through but still the same exception: 

zone.js:881 GET http://localhost:3000/angular-google-place 404 (Not Found)
(index):17 Error: Fetch error: 404 Not Found
  Instantiating http://localhost:3000/angular-google-place
  Loading http://localhost:3000/app/app.module.js
  Loading http://localhost:3000/app/boot.js

**Comment by psykolm22** [comment]
What is your stackflow ?

**Comment by owilkening** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:17 Error: Fetch error: 404 Not Found
  Instantiating http://localhost:3000/angular-google-place
  Loading http://localhost:3000/app/app.module.js
  Loading http://localhost:3000/app/boot.js
  Loading app
    at http://localhost:3000/node_modules/systemjs/dist/system.src.js:1500:13 [<root>]
    at <anonymous> [<root>]
(anonymous) @ localhost/:17

That's all I can see in the Chrome console

**Comment by psykolm22** [comment]
Can you explain a little bit about , how you app is managed ( angular CLI / webpack / systemJS  ) ? Which version of angular-google-place is installed into your node_modules and which version of Angular did you used ?

**Comment by owilkening** [comment]
My app is managed by systemJS, angular-google-place is installed with version 0.0.2 and I am using Angular in version 4.1.0.

Kind regards
Oliver

**Comment by owilkening** [comment]
It is working now:

package.json:
systemjs": "0.20.19",
"angular-google-place": "0.0.3"

systemjs.config.js in map:
'angular-google-place': "/node_modules/angular-google-place/bundles/angular-google-place.umd.js"

Cheers
Oliver
